##===- projects/opcstats/tools/opcstats/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=Opcstats

#
# List libraries that we'll need
# We use LIBS because opcstats is a dynamic library.
#
USEDLIBS = opcstats.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

