##===- projects/mcpre/tools/mcpre/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=Mcpre

#
# List libraries that we'll need
# We use LIBS because mcpre is a dynamic library.
#
USEDLIBS = mcpre.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

